### ISSUE TITLE
[190614, Feedback], range-sum-of-bst (ver. daim)

### ISSUE THREAD

**Issue by histuckyi** [2kindsofcs/daily-algo-challenge#1]
재귀 함수로 푸는 솔루션과 while loop 문으로 푸는 방법 두가지를 올려두었습니다.
코드 보시고 피드백 부탁드립니다.
개인적으로는 다른 분들이 제 코드를 이해하기 쉬운지가 궁금하네요.

[range-sum-of-bst 코드 보러 가기](https://github.com/2kindsofcs/daily-algo-challenge/blob/master/daim/190614_938.py)

**Comment by 2kindsofcs** [comment]
@histuckyi  코드 잘 보았습니다. ^^

Solution1
- if 1 < root.val < r: 이하 부분에서 result에 왼쪽 하위트리 총합과 오른쪽 총합 값이 더해지는 것이 아니라 왼쪽 총합을 할당한 뒤, 아래 행에서 오른쪽 총합을 할당하고 있습니다. 이 부분이 잘 이해가 되지 않습니다.  설명해주시면 감사하겠습니다. 


Solution2
- solution1보다는 이해가 잘 됩니다.  
- 다만 리스트를 위한 메모리를 할당하여 계속 요소를 넣고 뽑기를 반복하고 있어서, 메모리를 소모가 클 것 같습니다.

**Comment by histuckyi** [comment]
@2kindsofcs 님, 먼저 피드백 감사합니다.

Solution1
- 제가 이해한 바로는 @2kindsofcs 님과 저는 재귀를 사용하여 하위 트리가 없는 리프 노드까지 찾아들어가는 방식은 동일하지만, 조건에 맞는 값을 더하는 시점이 다르기 때문에 서로의 코드가 이해하기 어려운 것 같습니다.

- histuckyi : 조건에 맞는 값은 바로 더해나가고 그 총합을 checkChildBST의 result라는 인자값으로 전달. 
리프노드에 도달 시 이미 총합이 계산되어 있으므로 그 값인 result를 반환함.
- 2kindsofcs : 하위 트리가 없는 리프 노드까지 재귀가 진행되고 재귀를 빠져나가면서 그 값을 더해나가는 구조.
재귀를 모두 빠져나가야 총합이 계산됨.

정리하자면, 저는 왼쪽 총합을 구하고 오른쪽 총합을 구해서 두 값을 더하는게 아니라, 왼쪽 총합을 구한 값을 오른쪽 트리를 탐색할 때 result로 전달해주어 총합을 더해나가기 때문에 이해하기 어려우셨던 것 같습니다. @2kindsofcs님께서 동적 계획법으로 문제를 잘 풀어 주신거라, 질문해주신 덕분에 제가 한번 더 깊이 생각할 수 있었습니다. 감사합니다.

Solution2
-  이 문제의 두 코드에서는 재귀를 사용하는 것과 비교했을 때 메모리 소모 차이는 나지 않습니다. 
(재귀 코드 : 21.9MB,  반복문 :  21.7MB)
- 그 이유는, 재귀 호출 시 스택 메모리에 호출한 함수가 쌓일때마다 활성 레코드에 현재의 상태 정보를 저장하여야 하는데, 그때 사용하는 메모리와 반복문에서 리스트를 사용하는 메모리의 크기가 비슷하기 때문이라고 생각합니다.
-  만약 재귀 함수에서 선언한 변수가 많을 경우, 기억해야 하는 상태 정보들이 많아지므로 그 때는 재귀 함수와 반복문의 메모리 사용량이 많이 차이가 나지 않을까 싶습니다.
- 스택 메모리에 저장된 함수가 pop되면서 Context Switching이 일어나는 수행 시간을 고려한다면 재귀보다는 반복문을 사용하는게 가장 좋다는 글을 본 적이 있습니다.
- 사실 다른 플랫폼에서 파이썬으로 문제를 풀 때, Maximum Recursion depth exceed를 보는게 너무 괴로워서 재귀보다는 반복문으로 푸는 연습을 하는 중입니다. 모든 재귀는 반복문으로 개선할 수 있다더라구요.

**Comment by 2kindsofcs** [comment]
설명을 들으니 이제 이해가 됩니다. 인자로 들어가니까 이미 sum값은 계산이 되어 있는 거군요. 확실히 타인의 코드를 보는 연습이 되어서 좋네요.  자세한 답변 감사합니다.
