### ISSUE TITLE
 [190614 Feedback] range-sum-of-bst (ver. 2kindsofcs)

### ISSUE THREAD

**Issue by 2kindsofcs** [2kindsofcs/daily-algo-challenge#2]
피드백 있으실경우 코멘트로 작성 부탁드립니다. 

코드보기: [190614](https://github.com/2kindsofcs/daily-algo-challenge/blob/master/2kindsofcs/190614-range-sum-of-bst.py)

**Comment by histuckyi** [comment]
먼저 @2kindsofcs, 제 코드를 피드백 해주셔서 감사합니다!

- 중첩해서 함수를 작성하셨던데 그렇게 작성하신 이유가 있나요? 저는 보통 헬퍼 함수를 작성해서 호출하는 편인데 중첩 함수를 작성하였을 때의 장점이 있는건지 궁금합니다.

**Comment by 2kindsofcs** [comment]
@histuckyi  자세한 코멘트 감사합니다. 확실히 재귀함수가 메모리를 많이 잡아먹는군요. 저도 재귀를 쓰지 않고 while로 쓰는 연습을 다음에 해봐야겠습니다.

일단 중첩 함수의 장점은 밖에서 중첩 함수에 접근을 할 수 없고, 중첩 함수는 상위 함수의 매개변수에 접근할 수 있다는 것입니다. 다만 이 문제에서 중첩 함수를 꼭 써야 할 필요는 없었던 것 같은데, 본능적으로 이게 더 편하게 느껴져서 중첩 함수로 풀었네요. 질문 주신 것을 듣고 코드를 살짝 고쳐놓았습니다.

**Comment by histuckyi** [comment]
피드백 내용과 고쳐주신 코드 잘 보았습니다! 감사합니다
